sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dimple05081992/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dimple05081992/docker-react npm run test

# Deploy
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-i-0245c3d53cbe8a671'
  bucket_path: 'docker'
   on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
